### PR TITLE
PR RibomBalt / vscode-matlab-interactive-terminal implementing shared matlab sessions

### PR DESCRIPTION
**Pull request by phgmacedo**
There's a fork of the extension that implements improvements to the extension handling of matlab sessions. 

I could not find that version on the extension store. 

It would be nice to merge the improvements from there.

### CODE REVIEW

**Comment by phgmacedo** [comment]
@4086606 Do you know if you can add to this PR? 

I think it would be easier though if you forked the fork, and then submitted a new PR.

**Comment by 4086606** [comment]
Will do! Although I want to add SVG preview in [VSC core](https://github.com/microsoft/vscode/tree/main/extensions/image-preview) before that

**Comment by apommel** [comment]
I agree with @4086606. Shared Matlab sessions is not something I would use myself, but I would not mind if it was implemented. However, the way it is done here is quite messy (I mean even more than what I did), so I'd rather see it done in a cleaner way.

**Comment by apommel** [comment]
Because the implementation now conflicts with the current master I will close it, as it probably needs to be redone from scratch. Further discussion should probably go in #26.

**Pull request closed without merging**
