### PR TITLE
Categorise extension commands and add tests

### PR DESCRIPTION
**Pull request by SNDST00M**
Maybe a CI workflow should be added? It's really simple to do:

https://code.visualstudio.com/api/working-with-extensions/continuous-integration

### CODE REVIEW

**Comment by apommel** [comment]
I guess the CI could be added to check if it builds but for the tests it would need to have Matlab in the pipeline and I am not sure how that would work.

**Comment by SNDST00M** [comment]
Mathworks has provided a CI but I suppose it can't be covered under this pull

**Comment by SNDST00M** [comment]
I'm happy to buy MATLAB and become a maintainer here, I'm good for it :)

**Comment by SNDST00M** [comment]
I went and used the free GitHub Actions workflow. Should work, will test tomorrow to confirm that it does

**Comment by SNDST00M** [comment]
This is indefinitely on ice 😦 until MATLAB add their licensing scheme to MATLAB Engine for Python

**Pull request closed without merging**
