### PR TITLE
Show the error message returned by Matlab

### PR DESCRIPTION
**Pull request by ObserverAlpha**

### CODE REVIEW

**Comment by apommel** [comment]
Hello! Could you give some examples in which this behavior would be desirable? The Matlab error messages are supposed to be returned by the standard input/output and this modification would only display the Python exceptions returned by the Matlab engine, right?

**Comment by ObserverAlpha** [comment]
In Matlab Console: 
image

Before: 
image

After:
image


Matlab error message (the Chinese sentences on the underside of return) seems not returned by standard output. It's returned as the Python exception. This modification will display it.

**Comment by apommel** [comment]
The message is normally displayed, the issue lies with the fact that your system language is Chinese (similar to #5). I did some tests related to that and it seems that the Matlab Engine for Python does not support Unicode, which creates problems with CJK characters. Matlab encoding actually depends on the computer's locale, so I think it may be related to that. The solution would be to detect the system locale at runtime and reencode the strings accordingly but that's a bit heavy.
However, it seems that R2020a shifts the encoding to UTF-8, which should resolve it, could you give it a try? I will do the same.

In the current state, this PR would give a temporary solution, but would at the same time introduce unwanted output for users with roman characters locales.

**Comment by apommel** [comment]
R2020b did not solve the problem of CJK characters for me, but I managed to fix it in the latest update. Could you confirm me that you correctly get error messages this way?

**Comment by ObserverAlpha** [comment]
You are right. It's about the display of CJK characters. But R2020a seems still doesn't solve this problem. The [3 screenshots above](https://github.com/apommel/vscode-matlab-interactive-terminal/pull/7#issuecomment-614531362) were under R2020a. 

I tried to switch the language of Matlab R2020a into English and the error messages are normally displayed. This modification will display an extra content under this condition. 

image

Maybe it's better to use some conditional statements in the `Exception`.

**Pull request closed without merging**
